repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [manual]
      - id: end-of-file-fixer
        stages: [manual]
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      - id: check-ast # Ensures Python files are valid syntax
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf] # Force Linux style line endings

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: tests/example_.*\.py$
        stages: [manual]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: tests/example_.*\.py$
        stages: [manual]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: tests/example_.*\.py$
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        exclude: tests/example_.*\.py$
        stages: [manual]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        exclude: tests/example_.*\.py$
        stages: [manual]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: tests/
        stages: [manual]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        exclude: tests/example_.*\.py$
        stages: [manual]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        exclude: tests/example_.*\.py$
        additional_dependencies: ["pylint-pytest"]
        args: [
            "--disable=C0103,C0111", # Disable specific messages
            "--good-names=i,j,k,ex,Run,_",
            "--max-line-length=100",
          ]
        stages: [manual]

  - repo: local
    hooks:
      - id: version-sync
        name: Verify version numbers are in sync
        description: Check that the version in pyproject.toml is reported correctly
        entry: python .pre-commit-hooks/sync_version.py
        language: python
        files: ^pyproject\.toml$
        additional_dependencies: [tomli]
